properties:
  iteration_limit: 100
  return_first: false
  time_limit: 120
  C: 1.4
  cutoff_cumulative: 0.995
  cutoff_number: 50
  max_transforms: 6
  search_algorithm: "aizynthfinder.search.retrostar.search_tree.SearchTree"
policy:
  files:
    my_policy:
      - /home/sshorewala_umass_edu/scratch/aizynthfinder/config_files/Neuralsim/saved_rollout_state_1_2048.ckpt
      - /home/sshorewala_umass_edu/scratch/aizynthfinder/config_files/uspto_templates.hdf5
filter:
  files:
    my_policy: 
  reactants_count:
    filter_tag:
stock:
  files:
    zinc: /home/sshorewala_umass_edu/scratch/aizynthfinder/config_files/zinc_stock.hdf5
